// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC7hP-wYZz9Eka2rVjgAKsvgeYEtz1L2o',
    appId: '1:177351045579:web:e2539c87909bd1cb1e064e',
    messagingSenderId: '177351045579',
    projectId: 'mobile-proj-95615',
    authDomain: 'mobile-proj-95615.firebaseapp.com',
    storageBucket: 'mobile-proj-95615.firebasestorage.app',
    measurementId: 'G-MW53HSS0DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQaOkIgAZaPUhbCwibhsedysNsgwk5OdM',
    appId: '1:177351045579:android:2d184eeb6c72de7e1e064e',
    messagingSenderId: '177351045579',
    projectId: 'mobile-proj-95615',
    storageBucket: 'mobile-proj-95615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwBQeca2CC3ZkMcf0NyMXlv-1ZuLmal_U',
    appId: '1:177351045579:ios:1e196d5b4c22d91d1e064e',
    messagingSenderId: '177351045579',
    projectId: 'mobile-proj-95615',
    storageBucket: 'mobile-proj-95615.firebasestorage.app',
    iosBundleId: 'com.example.tuitionManagementSystem',
  );
}
